name: NuGet Package

on:
  workflow_dispatch

env:
  VERSION: 1.0.0

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check Out Repo
              uses: actions/checkout@v1

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: "6.0.x"

            - name: Restore NuGet packages
              run: dotnet restore

            - name: Build
              run: dotnet build Core/EventSourcing.NetCore.Core.sln --configuration Release /p:Version=$VERSION --no-restore

            - name: Pack
              run: dotnet pack Core/Core.csproj --configuration Release /p:Version=$VERSION --no-build --output .

            - name: Push
              run: dotnet nuget push STEGK.Forked.EventSourcing.NetCore.Core.$VERSION.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
              env:
                GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
