name: NuGet Package

on: workflow_dispatch

env:
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Version number
      run: echo VERSION=$VERSION
    - name: Build
      run: dotnet build Core/EventSourcing.NetCore.Core.sln --configuration Release /p:Version=$VERSION
    - name: Solution finished
      run: echo VERSION=$VERSION
    - name: Pack
      run: dotnet pack Core/Core.csproj --configuration Release /p:Version=$VERSION --no-build --output .
    - name: Core project packaged
      run: echo VERSION=$VERSION
    - name: Push
      run: dotnet nuget push STEGK.Forked.EventSourcing.NetCore.Core.$VERSION.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
